title = "fetch"
gitSourceBranch = "main"

[footer]
style = "dark"
copyright = "Copyright © 2023 TypeError. Built with Moonwave and Docusaurus"

[home]
enabled = true

[[home.features]]
title = "Simple"
description = "rbx-fetch has a simple API, counting 3 functions"

[[home.features]]
title = "Typed"
description = "rbx-fetch has types for options, responses and even HTTP methods"

[[home.features]]
title = "Promise-based"
description = "rbx-fetch deals with asynchronous operations using Promise"