title = "fetch"
gitSourceBranch = "main"

classOrder = [
    "fetch",
    "Response"
]

[footer]
style = "dark"
copyright = "Copyright © 2023 TypeError. Built with Moonwave and Docusaurus"

[home]
enabled = true

[[home.features]]
title = "Simple yet useful"
description = "rbx-fetch has a simple API, but also allows you to work with PNGs, JSON and text"

[[home.features]]
title = "Typed"
description = "rbx-fetch has types for options, responses, HTTP methods, and more!"

[[home.features]]
title = "Promise-based"
description = "rbx-fetch deals with asynchronous operations using Promise"