local ReplicatedStorage = game:GetService("ReplicatedStorage")
local fetch = require(ReplicatedStorage.Packages.fetch)

fetch("https://dummyjson.com/products/1")
	:andThen(function(response: fetch.Response)
		response.json():andThen(function(product)
			print(product)
		end)
	end)
	:catch(function(response: fetch.Response)
		warn("Failed to fetch data")
		response.json():andThen(function(product)
			warn(product)
		end)
	end)

fetch("https://rojo.space/img/logo.png")
	:andThen(function(response: fetch.Response)
		response.image():andThen(function(image: fetch.PNG)
			print(image.Width, image.Height)
		end)
	end)
	:catch(function(response: fetch.Response)
		warn("Failed to fetch data")
	end)
